# wget -O tsm/checkpoints/fastvit/fastvit_t8_reparam.pth.tar "https://docs-assets.developer.apple.com/ml-research/models/fastvit/image_classification_distilled_models/fastvit_t8_reparam.pth.tar"
# wget -O tsm/checkpoints/fastvit/fastvit_t12_reparam.pth.tar "https://docs-assets.developer.apple.com/ml-research/models/fastvit/image_classification_distilled_models/fastvit_t12_reparam.pth.tar"
# wget -O tsm/checkpoints/fastvit/fastvit_s12_reparam.pth.tar "https://docs-assets.developer.apple.com/ml-research/models/fastvit/image_classification_distilled_models/fastvit_s12_reparam.pth.tar"
# wget -O tsm/checkpoints/fastvit/fastvit_sa12_reparam.pth.tar "https://docs-assets.developer.apple.com/ml-research/models/fastvit/image_classification_distilled_models/fastvit_sa12_reparam.pth.tar"
# wget -O tsm/checkpoints/fastvit/fastvit_sa24_reparam.pth.tar "https://docs-assets.developer.apple.com/ml-research/models/fastvit/image_classification_distilled_models/fastvit_sa24_reparam.pth.tar"
# wget -O tsm/checkpoints/fastvit/fastvit_sa36_reparam.pth.tar "https://docs-assets.developer.apple.com/ml-research/models/fastvit/image_classification_distilled_models/fastvit_sa36_reparam.pth.tar"
wget -O tsm/checkpoints/fastvit/fastvit_ma36_reparam.pth.tar "https://docs-assets.developer.apple.com/ml-research/models/fastvit/image_classification_distilled_models/fastvit_ma36_reparam.pth.tar"

# wget -O tsm/checkpoints/fastvit/fastvit_t8.pth.tar "https://docs-assets.developer.apple.com/ml-research/models/fastvit/image_classification_distilled_models/fastvit_t8.pth.tar"
# wget -O tsm/checkpoints/fastvit/fastvit_t12.pth.tar "https://docs-assets.developer.apple.com/ml-research/models/fastvit/image_classification_distilled_models/fastvit_t12.pth.tar"
# wget -O tsm/checkpoints/fastvit/fastvit_s12.pth.tar "https://docs-assets.developer.apple.com/ml-research/models/fastvit/image_classification_distilled_models/fastvit_s12.pth.tar"
# wget -O tsm/checkpoints/fastvit/fastvit_sa12.pth.tar "https://docs-assets.developer.apple.com/ml-research/models/fastvit/image_classification_distilled_models/fastvit_sa12.pth.tar"
# wget -O tsm/checkpoints/fastvit/fastvit_sa24.pth.tar "https://docs-assets.developer.apple.com/ml-research/models/fastvit/image_classification_distilled_models/fastvit_sa24.pth.tar"
# wget -O tsm/checkpoints/fastvit/fastvit_sa36.pth.tar "https://docs-assets.developer.apple.com/ml-research/models/fastvit/image_classification_distilled_models/fastvit_sa36.pth.tar"
wget -O tsm/checkpoints/fastvit/fastvit_ma36.pth.tar "https://docs-assets.developer.apple.com/ml-research/models/fastvit/image_classification_distilled_models/fastvit_ma36.pth.tar"